name: React-CI-CD.yaml

on:
  push:
  #  branches: [ "main" ]
    tags:
      - "v1*"
  workflow_dispatch:

env:
  AWS_PRIVATE_IP: 172.31.30.63 #change it to have your private IP

jobs:
  pre-requisites:
    name: Pre-requisites Stage
    runs-on: [self-hosted, cicd]

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REACT_DEMO }}

      - name: Pull latest code and set script permissions
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.AWS_PRIVATE_IP }} << 'EOF'
            rm -rf /home/ubuntu/Udemy-section*
            git clone https://github.com/sagarkakkalasworld/Udemy-section5.git
            cd Udemy-section5
            chmod 744 build.sh
            chmod 744 deploy.sh
          EOF

  build:
    name: Build Stage
    needs: pre-requisites
    runs-on: [self-hosted, cicd]

    steps:
      - name: Run build.sh
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.AWS_PRIVATE_IP }} "bash /home/ubuntu/Udemy-section5/build.sh"

  deploy:
    name: Deploy Stage
    needs: build
    runs-on: [self-hosted, cicd]

    steps:
      - name: Run deploy.sh
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.AWS_PRIVATE_IP }} "bash /home/ubuntu/Udemy-section5/deploy.sh"
