name: React-CI-CD.yaml

on:
  push:
    branches: [ "main" ]

env:
  DEMO_SERVER: 172.31.30.63 #change it to have your private IP

jobs:
  pre-requisites:
    name: Pre-requisites Stage
    runs-on: [self-hosted, demo]

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REACT_DEMO }}

      - name: Pull latest code and set script permissions
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.DEMO_SERVER }} << 'EOF'
            cd /home/ubuntu/Udemy-section4-code
            git pull
            chmod 744 build.sh
            chmod 744 deploy.sh
          EOF

  build:
    name: Build Stage
    needs: pre-requisites
    runs-on: [self-hosted, demo]

    steps:
      - name: Run build.sh
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.DEMO_SERVER }} "bash /home/ubuntu/Udemy-section4-code/build.sh"

  deploy:
    name: Deploy Stage
    needs: build
    runs-on: [self-hosted, demo]

    steps:
      - name: Run deploy.sh
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.DEMO_SERVER }} "bash /home/ubuntu/Udemy-section4-code/deploy.sh"
